version: "3"
services:
  boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: python-ingress-boilerplate
      EGRESS_URL: https://hookb.in/r1YwjDyn7BHzWWJVK8Gq
      HANDLER_PORT: 80
      OUTPUT_LABEL: "temp"
      OUTPUT_UNIT: "Celsius"
    ports:
      - 5000:80
