version: "3"
services:
  serial-ingress:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: serial-ingress
      MODULE_TYPE: INGRESS
      EGRESS_URL: https://hookb.in/3OYoaZXXV9c7yakkyyM6
      PORT: /dev/cu.usbserial-130
      BAUD_RATE: 115200
    ports:
      - 5000:80
